version: "3"
services:
  backend:
    build: ../backend
    ports: [ "8000:8000" ]
    env_file:
      - .env
  web-admin:
    build: ../web-admin
    ports: [ "3000:3000" ]
  web-user:
    build: ../web-user
    ports: [ "3001:3000" ]
  mobile:
    image: cirrusci/flutter:latest
    volumes:
      - ../mobile:/app
    working_dir: /app
    command: flutter build apk
