# ~/ChameleonVPN/docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    container_name: chameleon_backend
    # Log klasörlerini oluştur + uvicorn
    command: >
      /bin/sh -lc 'mkdir -p /app/app/logs /var/log/backend &&
      chmod -R 777 /app/app/logs /var/log/backend &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - LOG_DIR=/app/app/logs
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./logs/backend:/var/log/backend

  db:
    image: postgres:14
    container_name: chameleon_db
    environment:
      POSTGRES_DB: chameleonvpn
      POSTGRES_USER: vpnadmin
      POSTGRES_PASSWORD: iryna
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: chameleon_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
