services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: chameleonvpn
      POSTGRES_USER: vpnadmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iryna}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpnadmin -d chameleonvpn"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # Şemayı head'e taşıyan tek-seferlik job
  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /srv
    entrypoint: ["bash","-lc","alembic -c alembic.ini upgrade head && alembic -c alembic.ini current -v"]
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg2://vpnadmin:${POSTGRES_PASSWORD:-iryna}@db:5432/chameleonvpn
    volumes:
      - ./backend/alembic:/srv/alembic:ro
      - ./infra/secrets:/app/secrets:ro
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]   # alembic migrate job ayrı
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg2://vpnadmin:${POSTGRES_PASSWORD:-iryna}@db:5432/chameleonvpn
      REDIS_URL: redis://redis:6379/0
      ALLOWED_ORIGINS: '["http://localhost","http://127.0.0.1","https://chameleonvpn.app","https://www.chameleonvpn.app"]'
      FIREBASE_PROJECT_ID: chameleonvpn-aba53
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/serviceAccount.json
    volumes:
      - ./infra/secrets:/app/secrets:ro
      - ./backend/alembic:/srv/alembic:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./frontend/web-admin/build:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: sh
    command: -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h; done'
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  certbot-etc:
  certbot-www:
