services:
  # --- PostgreSQL veritabanı ---
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: chameleonvpn
      POSTGRES_USER: vpnadmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpnadmin -d chameleonvpn"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  # --- Redis ---
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # --- Alembic migrate (tek seferlik) ---
  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ["alembic", "-c", "alembic.ini"]
    command: ["upgrade", "head"]
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg2://vpnadmin:${POSTGRES_PASSWORD}@db:5432/chameleonvpn
    volumes:
      - ./backend:/app
      - ./infra/secrets:/app/secrets:ro
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  # --- Backend (FastAPI) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    entrypoint: ["/entrypoint.sh"]
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg2://vpnadmin:${POSTGRES_PASSWORD}@db:5432/chameleonvpn
      REDIS_URL: redis://redis:6379/0
      ALLOWED_ORIGINS: '["http://localhost","http://127.0.0.1","https://chameleonvpn.app","https://www.chameleonvpn.app"]'
      FIREBASE_PROJECT_ID: chameleonvpn-aba53
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/serviceAccount.json
    volumes:
      - ./backend:/app
      - ./infra/secrets:/app/secrets:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    restart: unless-stopped

  # --- Web (Nginx reverse proxy + static hosting) ---
  web:
    image: nginx:alpine
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/web-admin/dist:/usr/share/nginx/html:ro
      - ./frontend/root:/usr/share/nginx/root:ro
      - ./deploy/nginx/chameleon.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    working_dir: /usr/share/nginx
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # --- Certbot (Let's Encrypt otomatik yenileme) ---
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./deploy/certbot/renew_hook.sh:/renew_hook.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sh
    command: -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook "/renew_hook.sh"; sleep 12h; done'
    restart: unless-stopped

# --- Volume tanımları ---
volumes:
  pgdata:
  redisdata:
  certbot-etc:
  certbot-www:
