# ~/ChameleonVPN/docker-compose.yml

services:
  backend:
    build:
      context: ./backend
    container_name: chameleon_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - ./backend:/app

  db:
    image: postgres:14
    container_name: chameleon_db
    environment:
      POSTGRES_DB: chameleonvpn
      POSTGRES_USER: vpnadmin
      POSTGRES_PASSWORD: iryna
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: chameleon_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
