global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']
  - job_name: database
    static_configs:
      - targets: ['db:9187']
