"""create peers table

Revision ID: 43c646ce1bfa
Revises: 2aa9a74d7751
Create Date: 2025-08-24 15:39:17.050431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c646ce1bfa'
down_revision: Union[str, Sequence[str], None] = '2aa9a74d7751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('assigned_ip', sa.String(length=64), nullable=True),
    sa.Column('allowed_ips', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assigned_ip'),
    sa.UniqueConstraint('public_key')
    )
    op.create_index(op.f('ix_peers_id'), 'peers', ['id'], unique=False)
    op.create_index(op.f('ix_peers_user_id'), 'peers', ['user_id'], unique=False)
    op.drop_table('alembic_version')
    op.alter_column('ai_server_selection_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('anomaly_fraud_records', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('anomaly_fraud_records', sa.Column('reason', sa.String(length=256), nullable=False))
    op.add_column('anomaly_fraud_records', sa.Column('detail', sa.String(length=256), nullable=True))
    op.alter_column('anomaly_fraud_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_anomaly_fraud_records_user_id', table_name='anomaly_fraud_records')
    op.create_foreign_key(None, 'anomaly_fraud_records', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('anomaly_fraud_records', 'is_fraud')
    op.drop_column('anomaly_fraud_records', 'severity')
    op.drop_column('anomaly_fraud_records', 'details')
    op.drop_column('anomaly_fraud_records', 'note')
    op.drop_column('anomaly_fraud_records', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_fraud_records', sa.Column('action', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('anomaly_fraud_records', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('anomaly_fraud_records', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('anomaly_fraud_records', sa.Column('severity', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('anomaly_fraud_records', sa.Column('is_fraud', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'anomaly_fraud_records', type_='foreignkey')
    op.create_index('ix_anomaly_fraud_records_user_id', 'anomaly_fraud_records', ['user_id'], unique=False)
    op.alter_column('anomaly_fraud_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('anomaly_fraud_records', 'detail')
    op.drop_column('anomaly_fraud_records', 'reason')
    op.drop_column('anomaly_fraud_records', 'ip_address')
    op.alter_column('ai_server_selection_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_index(op.f('ix_peers_user_id'), table_name='peers')
    op.drop_index(op.f('ix_peers_id'), table_name='peers')
    op.drop_table('peers')
    # ### end Alembic commands ###
