"""

Revision ID: c4531481299d
Revises: beb3b7fa379b
Create Date: 2025-08-22 11:01:56.500324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4531481299d'
down_revision: Union[str, Sequence[str], None] = 'beb3b7fa379b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('wg_quick', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['vpn_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_configs_id'), 'vpn_configs', ['id'], unique=False)
    op.create_index(op.f('ix_vpn_configs_server_id'), 'vpn_configs', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_configs_server_id'), table_name='vpn_configs')
    op.drop_index(op.f('ix_vpn_configs_id'), table_name='vpn_configs')
    op.drop_table('vpn_configs')
    # ### end Alembic commands ###
