"""sync user relationships & notifications

Revision ID: e6daa7f6d875
Revises: e99d94414028
Create Date: 2025-08-10 12:06:19.658894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6daa7f6d875'
down_revision: Union[str, Sequence[str], None] = 'e99d94414028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_corporate_rights_changed_by', 'corporate_user_rights_history', ['changed_by_admin_id'], unique=False)
    op.create_index('ix_corporate_rights_user_id', 'corporate_user_rights_history', ['user_id'], unique=False)
    op.add_column('user_relationships', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('user_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_index('ix_user_relationships_related_user_id', 'user_relationships', ['related_user_id'], unique=False)
    op.create_index('ix_user_relationships_user_id', 'user_relationships', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_rel_type', 'user_relationships', ['user_id', 'related_user_id', 'relationship_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_rel_type', 'user_relationships', type_='unique')
    op.drop_index('ix_user_relationships_user_id', table_name='user_relationships')
    op.drop_index('ix_user_relationships_related_user_id', table_name='user_relationships')
    op.alter_column('user_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('user_relationships', 'created_at')
    op.drop_index('ix_corporate_rights_user_id', table_name='corporate_user_rights_history')
    op.drop_index('ix_corporate_rights_changed_by', table_name='corporate_user_rights_history')
    # ### end Alembic commands ###
