"""add user relationships and related models

Revision ID: e99d94414028
Revises: 3cca93b1327b
Create Date: 2025-08-10 11:55:26.222919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99d94414028'
down_revision: Union[str, Sequence[str], None] = '3cca93b1327b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_corporate_rights_changed_by', 'corporate_user_rights_history', ['changed_by_admin_id'], unique=False)
    op.create_index('ix_corporate_rights_user_id', 'corporate_user_rights_history', ['user_id'], unique=False)
    op.add_column('user_notifications', sa.Column('channel', sa.String(length=32), nullable=True))
    op.alter_column('user_notifications', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user_notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.alter_column('user_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('user_notifications_user_id_fkey'), 'user_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_notifications', 'users', ['user_id'], ['id'])
    op.drop_column('user_notifications', 'type')
    op.drop_column('user_notifications', 'status')
    op.add_column('user_relationships', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('user_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_index('ix_user_relationships_related_user_id', 'user_relationships', ['related_user_id'], unique=False)
    op.create_index('ix_user_relationships_user_id', 'user_relationships', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_rel_type', 'user_relationships', ['user_id', 'related_user_id', 'relationship_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_rel_type', 'user_relationships', type_='unique')
    op.drop_index('ix_user_relationships_user_id', table_name='user_relationships')
    op.drop_index('ix_user_relationships_related_user_id', table_name='user_relationships')
    op.alter_column('user_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('user_relationships', 'created_at')
    op.add_column('user_notifications', sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('user_notifications', sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_notifications', type_='foreignkey')
    op.create_foreign_key(op.f('user_notifications_user_id_fkey'), 'user_notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.alter_column('user_notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_notifications', 'message',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_notifications', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user_notifications', 'channel')
    op.drop_index('ix_corporate_rights_user_id', table_name='corporate_user_rights_history')
    op.drop_index('ix_corporate_rights_changed_by', table_name='corporate_user_rights_history')
    # ### end Alembic commands ###
