# backend/.github/workflows/ci.yml
name: FastAPI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları kur
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Testleri çalıştır
      run: |
        cd backend
        pytest
