package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.example.flutter_wireguard_plugin.FlutterWireguardPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_wireguard_plugin, com.example.flutter_wireguard_plugin.FlutterWireguardPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new id.laskarmedia.openvpn_flutter.OpenVPNFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin openvpn_flutter, id.laskarmedia.openvpn_flutter.OpenVPNFlutterPlugin", e);
    }
  }
}
