name: chameleon_vpn_client
description: "Chameleon VPN Flutter client"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http:
  openvpn_flutter:
  flutter_wireguard_plugin:
    path: ./plugins/flutter_wireguard_plugin
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/vpn_config.ovpn
