name: CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chameleonvpn/backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run backend tests
        run: pytest app/test_app.py

  mobile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chameleonvpn/mobile
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
      - name: Install dependencies
        run: flutter pub get
      - name: Run widget tests
        run: flutter test

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/web-admin
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
