name: Mobile Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Pub get
        run: flutter pub get
        working-directory: chameleon_vpn_client

      - name: Build APK
        run: flutter build apk --release
        working-directory: chameleon_vpn_client

      - name: SHA256
        run: sha256sum chameleon_vpn_client/build/app/outputs/flutter-apk/app-release.apk > app-release.apk.sha256

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            chameleon_vpn_client/build/app/outputs/flutter-apk/app-release.apk
            app-release.apk.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
