name: Mobile Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  android:
    name: Android AAB Build (no artifacts)
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.22.2"
      ANDROID_NDK_VERSION: "27.0.12077973"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -Dfile.encoding=UTF-8'"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Accept Android licenses
        run: yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Install Android NDK ${{ env.ANDROID_NDK_VERSION }}
        run: |
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" "ndk;${ANDROID_NDK_VERSION}"
          echo "ndk.dir=${ANDROID_SDK_ROOT}/ndk/${ANDROID_NDK_VERSION}" >> "${GITHUB_WORKSPACE}/chameleon_vpn_client/android/local.properties"

      - name: Flutter doctor (diagnostic)
        working-directory: chameleon_vpn_client
        run: flutter doctor -v

      - name: Pub get
        working-directory: chameleon_vpn_client
        run: flutter pub get

      # ❗ APK YOK — Resmi mağaza politikası gereği AAB build
      - name: Build AAB (release)
        working-directory: chameleon_vpn_client
        run: flutter build appbundle --release -v

      # ❗ Artefact / Release upload YOK — mağaza yüklemesi resmi kanaldan yapılacak
      - name: Policy guard (fail if APK sneaks in)
        run: |
          if git grep -nE 'flutter build apk|\.apk\b' -- ':!*.md' ':!*.yml' ':!*.yaml' ; then
            echo "APK build/upload forbidden by policy."; exit 1; fi
